### ISSUE TITLE
unreleased code require

### ISSUE THREAD

**Issue by cwy1005** [Xingwei-Tan/CALLMSAE#1]
I am very interested in this work.I have noticed that while some of the code has been made available on GitHub, there are still key components that have not been released. Gaining access to these parts of the codebase would be immensely beneficial to my project.
So I was wondering if there are plans to release the remaining parts of the code recently, I believe that having access to the full code would greatly assist my project.
I appreciate any information or guidance you can provide.
Thank you so much!

**Comment by Xingwei-Tan** [comment]
Hi, cwy1005

Thank you for being interested in our work. That's very encouraging.
The work is currently under review and I'm on an annual leave recently. So, it might need some time before releasing the complete code. Sorry for the inconvenience.

Best,

**Comment by pp-jia** [comment]
> Hi, cwy1005
> 
> Thank you for being interested in our work. That's very encouraging. The work is currently under review and I'm on an annual leave recently. So, it might need some time before releasing the complete code. Sorry for the inconvenience.
> 
> Best,

Hi, Tan

May I ask if you have finished your leave (T⌓T), When will the code be released?

Best,

**Comment by Xingwei-Tan** [comment]
Hi, 

Thanks for being interested in our work!
I have uploaded the prompting code.
I hope they help.

Best,
Xingwei

**Comment by 2662448726** [comment]
Hi, Tan

Thanks to the author team for such excellent work.
Here is a question about the dataset. The NYT dataset cannot be obtained now. Does the author have a backup of the dataset or provide the checkpoint of the model?
Looking forward to your reply.

Best,

**Comment by Xingwei-Tan** [comment]
> Hi, Tan
> 
> Thanks to the author team for such excellent work. Here is a question about the dataset. The NYT dataset cannot be obtained now. Does the author have a backup of the dataset or provide the checkpoint of the model? Looking forward to your reply.
> 
> Best,

Hi,

Unfortunately, the license of the NYT corpus doesn’t allow the users of the dataset like us to distribute the dataset freely. I’m not sure why the publisher stopped providing the data. Have you sent an email to them?

Best,
